{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from _future_ import print_function\n",
    "import numpy as np\n",
    "from keras.datasets import mnist\n",
    "from keras.models import Sequential\n",
    "from keras.layers.core import Dense, Activation\n",
    "from keras.optimizers import SGD\n",
    "from keras.utils import np_utils\n",
    "np.random.seed(1671) # for reproductibity\n",
    "\n",
    "# network and training\n",
    "\n",
    "NB_EPOCH = 20\n",
    "BATCH_SIZE = 128\n",
    "VERBOSE = 1\n",
    "NB_CLASSES = 10 # NUMBER OF OUTPUTS = NUMBER OF DIGITS\n",
    "OPTIMIZER = SGD() \n",
    "N_HIDDEN = 128\n",
    "\n",
    "VALIDATION_SPLIT = 0.2 # how much train is reversed for validation\n",
    "\n",
    "#data: shuffled and split between trtain and test sets\n",
    "#\n",
    "(X_train, y_train) , (X_test, y_test) = mnist.load_data()\n",
    "# Xtrain is 6000 rtows of 28x28 values --> reshaped in 60000 x 784 reshaped = 784\n",
    "#\n",
    "\n",
    "X_train = X_train.reshape(60000, RESHAPED )\n",
    "X_test = X_test.reshape(10000, RESHAPED )\n",
    "X_train = X_train.astype ('float 32')\n",
    "X_test = X_tests.astype ('float 32')\n",
    "#normalize\n",
    "\n",
    "#\n",
    "X_train /=255\n",
    "X_test /=255\n",
    "\n",
    "print (x_train.shape[0], 'train samples')\n",
    "print (x_test.shape[0], 'tests samples')\n",
    "#convert class vectors to binary class matrices\n",
    "\n",
    "Y_train = np_utils.to_categorical(y_train, NB_CLASSES)\n",
    "Y_test = np_utils.to_categorical(y_test, NB_CLASSES)\n",
    "\n",
    "\n",
    "\n",
    "model = Sequential()\n",
    "model.add(Dense(N_HIDDEN, input_shape = (RESHAPED, )))\n",
    "model.add(Activation('relu'))\n",
    "model.add(Dense(N_HIDDEN)\n",
    "model.add(Activation('relu'))\n",
    "model.add(Dense(NB_CLASSES))\n",
    "model.add(Activation('softmax'))\n",
    "model.summary()\n",
    "model.compile(loss='categorical_crossentropy', optimizer = OPTIMIZER, metrtics = ['accuracy'])\n",
    "\n",
    "history = model.fit(X_train, y_train, batch_size = BATCH_SIZE, epochs = NB_EPOCH, verbose = VERBOSE, validation_split\n",
    "= VALIDATION_SPLIT)\n",
    "          \n",
    "score = model.evaluate(x_test, y_test, verbose = VERBOSE)\n",
    "          \n",
    "print(\"Test score: \" , score [0])\n",
    "print(\"Test accuracy: \", score [1])\n",
    "\n",
    "          \n",
    "          \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
